### ISSUE TITLE
Libraries are missing in code

### ISSUE THREAD

**Issue by shaq86** [wizicer/UAPNetwork#1]
DMedia.NongXinTong.Common.SocketLibrar
DMedia.NongXinTong.Core.Portal.Router
DMedia.NongXinTong.Common.Components.Log
Amib.Threading

**Comment by evidsibi** [comment]
Hi Has anyone gotten access to this Libraries

**Comment by wizicer** [comment]
Hi guys, I'm surprised you are interested in this UAP library, In China, only several province are using UAP protocol to communicate USSD, most of other is using SMPP(in china called CMPP).

if you still interested in this source code, let me know, I can fix it.

**Comment by evidsibi** [comment]
Hi wizicer,

Am very interested with this code. Could you please provide me with the full library. Especially the following missing classes.

DMedia.NongXinTong.Common.SocketLibrar
DMedia.NongXinTong.Core.Portal.Router
DMedia.NongXinTong.Common.Components.Log
Amib.Threading

Regards,

**Comment by evidsibi** [comment]
Hi wizicer,  Any luck on getting those libraries

**Comment by wizicer** [comment]
although these library( which start with DMedia) is written by me, however to avoid the legal risk with my previous employer, I will remove the dependency to these library.

**Comment by evidsibi** [comment]
Do you have a library that we could use to replace the DMedia one

**Comment by wizicer** [comment]
I'm working on this recently, and synchronizing to the adoption_development branch.
however, I'm busy with my personal affairs recently, time is a problem. I'll try my best.

**Comment by wizicer** [comment]
Hi everybody, take a look at 29e63fa2881d212c0029f5154bc77788d854ff83

**Comment by evidsibi** [comment]
Thanks alot for the fix ... Could you be having the   Amib.Threading  Library

**Comment by wizicer** [comment]
if you installed nuget with VS, it should be installed automatically when you click "build", otherwise, you could check https://www.nuget.org/packages/SmartThreadPool.dll/
