### ISSUE TITLE
Unable to Send ContinueUAP Request.

### ISSUE THREAD

**Issue by tijanibro** [wizicer/UAPNetwork#3]
Hi Wizicer,

We are trying to use your codebase to implement USSD Application with a network operator in Nigeria, We can bind successful and get a bind response, However we are unable to respond to their BeginUAP request, We have looked at the Packet.cs file but couldn't figure out the issues. The request gets terminated with an AbortUAP from the network side. What could possibly be wrong in the Packets? Can I share the trace in an email?

**Comment by wizicer** [comment]
I'm on holiday now, I'll return after 8th Oct. Would take a look then.

**Comment by tijanibro** [comment]
Are you available now?

**Comment by wizicer** [comment]
For my understanding, if you get a AbortUAP packet, means you have some parameter not met server's expectation, can you check the parameter you send to server? (Especially the authentication information)

**Comment by tijanibro** [comment]
The Authentication parameters seems okay, as we can bind successfully. we do get a bind response, however when we try to send continueUAP request after the MS has sent the USSD string and a BeginUAP has reached our server, I believe the AbortUAP comes up when the USSDC expects a response and doesn't get it. Are you available for a chat via hangout?

**Comment by wizicer** [comment]
Let me just try to understanding you issue first, you have done this:
- Send `BindRequest` to gateway.
- Retrieve `BindResponse` from gateway with success information.
- User send USSD request to gateway.
- Your server receive `BeginUAP` from server.
- Your server response with `ContinueUAP` packet.
- Your server received `AbortUAP` and then **your connection actively refused by gateway?**

Sadly, hangout is not available in our country.

**Comment by tijanibro** [comment]
Yes you are correct except the last two.
- Our Server Receives BeginUap but unable to respond with ContinueUAP packets.

**Comment by tijanibro** [comment]
After sometime, we receive abortUAP meaning the USSDC aborts after waiting for the ContinueUAP but can't get it

We couldn't figure where the issue is  from the UAPtester code.

**Comment by wizicer** [comment]
What do you mean `unable to respond`, is that you tried to respond but gateway not received?

**Comment by tijanibro** [comment]
Yes, after I received beginUap, I have set continueUap from the tester app
but seems not to get to the gateway instead the gateway responds with an
AbortUap after waiting for sometimes.

**Comment by wizicer** [comment]
My suggestion is debug to track down to the raw socket to make sure your continue uap packet had sent successfully from tester program.

**Comment by tijanibro** [comment]
Thanks for the reply, Our major challenge is the inability to debug the
packet.cs app and figure out why the continueUAp does not get sent from the
tester application

**Comment by wizicer** [comment]
Are you able to do some logging and get the log file? If so, please add log to that specific point to make sure the continue uap packet had sent successfully.

**Comment by tijanibro** [comment]
Yes, we have logs, and we have set the point. It seems the ContinueUAP
packets is not emanating from the server.

**Comment by wizicer** [comment]
IMHO, this already off topic, in your situation, you should have better debugging skill to enable debugging on server without IDE.

You could add more logs and find where the program stuck.

**Comment by mbahmani** [comment]
Hi Guys, I have just started  to use this framework 
Can I make USSD  menus  with this framework?

**Comment by wizicer** [comment]
this is the communication layer protocol, didn't handle the logic in application layer like making menus. So you are free to create your own application upon this protocol stack.

**Comment by mbahmani** [comment]
thanks for your replying, these days I tired to use this framework, and make a server program to handle USSD....
Look at the following image

![image](https://user-images.githubusercontent.com/22489707/27275756-2091f8ec-54ee-11e7-8418-7bd875b5ff35.png)

does it  explain how framework works?
I've got **bindresp** and I think,  I  make a  connection Successfully,  you can see it

![image](https://user-images.githubusercontent.com/22489707/27275991-da7ec866-54ee-11e7-8020-8ea6976e1f0d.png)


after that the program  falls down in --**while (Console.ReadLine() != "end")**--
furthermore, start to repeat these code since we should start communicate with user's phone 

-----------------------------------
  ```
 //UapContinue newUapContinue = new UapContinue()
                //{
                //    SenderId = seq++,
                //    ReceiverId = 0xffffffff,
                //    UssdVersion = UapBase.UssdVersionEnum.PhaseIIP,
                //    UssdOpType = UapBase.UssdOpTypeEnum.Request,
                //    MsIsdn = "@@",
                //    ServiceCode = "@@",
                //    CodeScheme = 0x44,
                //    UssdContent = "321"
                //};
                UapBegin newUapBegin = new UapBegin()
                {
                    SenderId = @@,// seq++,
                    ReceiverId = @@,
                    UssdVersion = UapBase.UssdVersionEnum.PhaseII,
                    UssdOpType = UapBase.UssdOpTypeEnum.Request,
                    MsIsdn = "@@",
                    ServiceCode = "@@",
                    CodeScheme = 0x48,
                    UssdContent = "@@"
                };
                communicator.SendUap(newUapBegin);
                //UapContinue con = new UapContinue()
                //{
                //    SenderId = seq++,
                //    ReceiverId = e.ContinueUap.SenderId,
                //    UssdVersion = e.ContinueUap.UssdVersion,
                //    UssdOpType = UapBase.UssdOpTypeEnum.Request,
                //    //UssdOpType = seq == 10 ? UapBase.UssdOpTypeEnum.Request : UapBase.UssdOpTypeEnum.Notify,
                //    MsIsdn = e.ContinueUap.MsIsdn,
                //    ServiceCode = e.ContinueUap.ServiceCode,
                //    CodeScheme = 0x11,
                //    UssdContent = "thanks for your input, again!" + seq +  ！"
                //};
                //communicator.SendUap(con);
```
-------------------------------------------------------------
could you explain this part of code? especially where I fill with @@

**Comment by wizicer** [comment]
you could find example here: https://github.com/wizicer/UAPNetwork/blob/master/UAPTester/Program.cs#L61

I thought the example with parameter should self explained.

**Comment by mbahmani** [comment]
thanks for your perfect example, you know I  got response

**Comment by mbahmani** [comment]
when I set UssdContent="Hi Guys"
I just get Chinese character in my phone? did you use any encoding for that? how can I change it to English?

**Comment by wizicer** [comment]
I guess you are getting some random character, not Chinese character. Every server could use different code scheme, you must assign the corresponding code scheme according to your server. 

Change this LOC: https://github.com/wizicer/UAPNetwork/blob/master/UAPTester/Program.cs#L69

**Comment by mbahmani** [comment]
I solved that by changing this line:
[https://github.com/wizicer/UAPNetwork/blob/master/UAPLibrary/Utility/StringUtility.cs#L49](url)
to 
`Encoding encoding = Encoding.UTF8;`
now , I don't have any problem for English language but for Persian language I couldn't solve that

**Comment by nathankamau** [comment]
Guys,
Do we have the USSD App Protocol implementation in java or node?

**Comment by wizicer** [comment]
close as it isn't a issue anymore

**Comment by dayokesola** [comment]
@tijanibro 
The issue you are having is here
![image](https://user-images.githubusercontent.com/12156786/58975151-312aca00-87bc-11e9-813c-3efc79ba7cf4.png)

Make sure the constants match the settings of your provider. In my case servicecode length is 21, and not 4
