### ISSUE TITLE
Unbind and rebind UapCommunicator

### ISSUE THREAD

**Issue by rontuku** [wizicer/UAPNetwork#8]
Hi, 
I would like to know how i can unbind and bind again the communicator without stopping or restarting the service in the UAPTester solution program.cs
Mutuku, Kenya

**Comment by wizicer** [comment]
UapCommunicator is disposable, just dispose it and create it again.
Hope this could solve your problem.

**Comment by rontuku** [comment]
Yes it has. Thank you Wizicer
